spring:
  profiles:
    active: local
--- ## api swagger 설정
spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
--- ## webflux swagger 설정
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  packages-to-scan: org.lgw.webfluxtoy.controller
  swagger-ui:
    path: swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  cache:
    disabled: true
---
spring:
  sql:
    init:
      mode: embedded
      schema-locations: classpath:database/schema.sql
  output:
    ansi:
      enabled: always
logging:
  level:
    dev.fastcampus: debug
    org.springframework.r2dbc.core: off
api:
  externalUrl: http://localhost:8081
---
spring:
  config:
    activate:
      on-profile: stress
  r2dbc:
    url: r2dbc:pool:mariadb://localhost:3306/webflux
    username: user
    password: 1234
  sql:
    init:
      mode: never
