
###
GET localhost:8080/getApiData?name=1234


###
GET http://localhost:8080/webflux/1
Content-type: application/json


###
GET {{domain}}/webflux/all
Content-type: application/json


###
POST localhost:8080/webflux/create
Content-type: application/json

{
"title": "test3",
"body": "3 테스트",
"authorId": "1234"
}

###

GET localhost:8080/webflux/all
Content-type: application/json


###
DELETE localhost:8080/webflux/1
Content-type: application/json